In [2]:
import os
import numpy as np
import pandas as pd
from IPython.display import display

In [10]:
df_A = pd.read_csv('../data/A.csv')
df_B = pd.read_csv('../data/B.csv')
df_C = pd.read_csv('../data/C.csv')
df_D = pd.read_csv('../data/D.csv')
display(df_A[:3])
display(df_B[:3])
display(df_C[:3])
display(df_D[:3])
print df_A.shape, df_B.shape, df_C.shape, df_D.shape

click_id  is_attributed
0         0       0.079476
1         1       0.019888
2         2       0.002251

click_id  is_attributed
0         0       0.074376
1         1       0.010013
2         2       0.001023

click_id  is_attributed
0         0       0.025129
1         1       0.003293
2         2       0.000273

click_id  is_attributed
0         0       0.038317
1         1       0.001390
2         2       0.000022

(18790469, 2) (18790469, 2) (18790469, 2) (18790469, 2)


In [11]:
delta = 1E-10
def sigmoid(x):
    1. / (np.exp(-x)+1.)
def upper(x):
    return min(x, 1.-delta)
def lower(x):
    return max(x, delta)
def rev(x):
    return -np.log(1./x - 1.)

In [12]:
%time df_A.is_attributed = df_A.is_attributed.apply(upper)
%time df_A.is_attributed = df_A.is_attributed.apply(lower)
%time df_A['coeff'] = df_A.is_attributed.apply(rev)
%time df_B.is_attributed = df_B.is_attributed.apply(upper)
%time df_B.is_attributed = df_B.is_attributed.apply(lower)
%time df_B['coeff'] = df_B.is_attributed.apply(rev)
%time df_C.is_attributed = df_C.is_attributed.apply(upper)
%time df_C.is_attributed = df_C.is_attributed.apply(lower)
%time df_C['coeff'] = df_C.is_attributed.apply(rev)
%time df_D.is_attributed = df_D.is_attributed.apply(upper)
%time df_D.is_attributed = df_D.is_attributed.apply(lower)
%time df_D['coeff'] = df_D.is_attributed.apply(rev)

CPU times: user 7.7 s, sys: 464 ms, total: 8.17 s
Wall time: 8.11 s
CPU times: user 6.96 s, sys: 298 ms, total: 7.26 s
Wall time: 7.19 s
CPU times: user 41.9 s, sys: 853 ms, total: 42.7 s
Wall time: 42.5 s
CPU times: user 7.65 s, sys: 373 ms, total: 8.02 s
Wall time: 7.87 s
CPU times: user 7.01 s, sys: 345 ms, total: 7.35 s
Wall time: 7.25 s
CPU times: user 42.5 s, sys: 832 ms, total: 43.4 s
Wall time: 43.1 s
CPU times: user 7.75 s, sys: 382 ms, total: 8.14 s
Wall time: 8.03 s
CPU times: user 7.13 s, sys: 389 ms, total: 7.52 s
Wall time: 7.36 s
CPU times: user 42.6 s, sys: 920 ms, total: 43.5 s
Wall time: 43.3 s
CPU times: user 7.69 s, sys: 337 ms, total: 8.02 s
Wall time: 7.92 s
CPU times: user 7.1 s, sys: 407 ms, total: 7.5 s
Wall time: 7.31 s
CPU times: user 42.3 s, sys: 880 ms, total: 43.2 s
Wall time: 42.9 s


In [ ]:
%%time
coeff_A = 0.8
coeff_B = 0.1
coeff_C = 0.05
coeff_D = 0.05
vec_A = np.array(df_A.is_attributed.tolist())
vec_B = np.array(df_B.is_attributed.tolist())
vec_C = np.array(df_C.is_attributed.tolist())
vec_D = np.array(df_D.is_attributed.tolist())
vec = vec_A*coeff_A + vec_B*coeff_B +  vec_C*coeff_C + vec_D*coeff_D
df_A.is_attributed = sigmoid(vec)
display(df_A[:3])

click_id is_attributed     coeff
0         0          None -2.449491
1         1          None -3.897545
2         2          None -6.094313

CPU times: user 10.7 s, sys: 1.53 s, total: 12.2 s
Wall time: 12.3 s


df = pd.DataFrame({
    "click_id": df_B.click_id.values,
    "is_attributed": ans
})
display(df[:3])
print df.shape

In [ ]:
%%time
filename = "../g_{0}_{1}_{2}_{3}.csv".format(coeff_A, coeff_B, coeff_C, coeff_D)
df_A.to_csv(filename, index=False)

In [4]:
A = []
A.append(np.array([1,2,3,4,5]))
A.append(np.array([1,2,3,4,5]))
A.append(np.array([1,2,3,4,5]))
A = np.array(A)
print A.shape
print A
C = np.zeros(3)
C = [0.1, 0.4, 0.5]

(3, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [8]:
np.dot(C, A)[0]

1.0

In [9]:
roc_auc_score

NameError: name 'roc_auc_score' is not defined

In [10]:
from sklearn.metrics import roc_auc_score

In [15]:
D = np.zeros(5)
E = np.dot(C, A)
D[3]=1
E = E/E.sum()
roc_auc_score(D, E)

0.75